### ISSUE TITLE
Give some Suggestions

### ISSUE THREAD

**Issue by xrdrsp** [xrdrsp-edit/oi#1]
I need some assistance. I would appreciate your help. Thanks.

**Comment by Dovuq** [comment]
about what?

**Comment by xrdrsp** [comment]
> about what?

anything.

**Comment by Dovuq** [comment]
> <https://github.com/Eunthique/oi/blob/master/index.md>

I suggest to rename this as index.html (

**Comment by Dovuq** [comment]
Is this oi.xrdrsp.pw? @xrdrsp

**Comment by xrdrsp** [comment]
> https://github.com/Eunthique/oi/blob/master/index.md

I appreciate it, and will do!

> Is this oi.xrdrsp.pw? @xrdrsp

Yes, sure.

**Comment by Dovuq** [comment]
nintql

**Comment by Dovuq** [comment]
@xrdrsp What are you planning to put here?

**Comment by xrdrsp** [comment]
> @xrdrsp What are you planning to put here?

OI solutions

**Comment by Dovuq** [comment]
> > @xrdrsp What are you planning to put here?
> 
> OI solutions

@xrdrsp then copy the code here!

**Comment by xrdrsp** [comment]
> > > @xrdrsp What are you planning to put here?
> > 
> > 
> > OI solutions
> 
> @xrdrsp then copy the code here!

Where?

**Comment by Dovuq** [comment]
/xxx/index.cpp

**Comment by xrdrsp** [comment]
> /xxx/index.cpp

Yea. I think I would upload html and Markdown and cpp file for a solution.

Thanks.

**Comment by Dovuq** [comment]
@xrdrsp 

You can put https://xrdrsp.home.blog/,

**Comment by xrdrsp** [comment]
Ah. You still remember that /kk

**Comment by Dovuq** [comment]
@xrdrsp u didn't see my "xrdrsp's blogs"? /xyx

**Comment by Dovuq** [comment]
test
